version: '2'
services:
  config-service:
    image: demo.spring.cloud/config-service:latest
    expose:
      - "8888"
    ports:
      - "8888:8888"
    networks:
      - microservices

  eureka-service:
    image: demo.spring.cloud/eureka-service:latest
    links:
      - config-service
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - microservices

  security-service:
    image: demo.spring.cloud/security-service:latest
    links:
      - config-service
      - eureka-service
    expose:
      - "8081"
    ports:
      - "8081:8081"
    networks:
      - microservices

  product-service:
    image: demo.spring.cloud/product-service:latest
    links:
      - config-service
      - eureka-service
      - security-service
    expose:
      - "8082"
    ports:
      - "8082:8082"
    networks:
      - microservices

  hystrix-dashboard:
    image: demo.spring.cloud/hystrix-dashboard:latest
    expose:
      - "8090"
    ports:
      - "8090:8090"
    networks:
      - microservices

  api-gateway:
    image: demo.spring.cloud/api-gateway:latest
    links:
      - security-service
      - product-service
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - microservices

networks:
  microservices: